sudo: required

services:
  - docker

env:
  - PLATFORM=ubuntu PLATFORM_VERSION=14.04 PACKAGECLOUD_DISTROS="ubuntu/trusty" KERNEL_ARCH=i386
  - PLATFORM=ubuntu PLATFORM_VERSION=14.04 PACKAGECLOUD_DISTROS="ubuntu/trusty" KERNEL_ARCH=x86_64
  - PLATFORM=ubuntu PLATFORM_VERSION=16.04 PACKAGECLOUD_DISTROS="ubuntu/quantal" KERNEL_ARCH=i386
  - PLATFORM=ubuntu PLATFORM_VERSION=16.04 PACKAGECLOUD_DISTROS="ubuntu/quantal" KERNEL_ARCH=x86_64
  - PLATFORM=ubuntu PLATFORM_VERSION=18.04 PACKAGECLOUD_DISTROS="ubuntu/bionic" KERNEL_ARCH=i386
  - PLATFORM=ubuntu PLATFORM_VERSION=18.04 PACKAGECLOUD_DISTROS="ubuntu/bionic" KERNEL_ARCH=x86_64
  - PLATFORM=ubuntu PLATFORM_VERSION=20.04 PACKAGECLOUD_DISTROS="ubuntu/focal" KERNEL_ARCH=i386
  - PLATFORM=ubuntu PLATFORM_VERSION=20.04 PACKAGECLOUD_DISTROS="ubuntu/focal" KERNEL_ARCH=x86_64
  - PLATFORM=centos PLATFORM_VERSION=6 PACKAGECLOUD_DISTROS="el/6" KERNEL_ARCH=i386
  - PLATFORM=centos PLATFORM_VERSION=6 PACKAGECLOUD_DISTROS="el/6" KERNEL_ARCH=x86_64
  - PLATFORM=centos PLATFORM_VERSION=7 PACKAGECLOUD_DISTROS="el/7" KERNEL_ARCH=i386
  - PLATFORM=centos PLATFORM_VERSION=7 PACKAGECLOUD_DISTROS="el/7" KERNEL_ARCH=x86_64
  - PLATFORM=centos PLATFORM_VERSION=8 PACKAGECLOUD_DISTROS="el/8" KERNEL_ARCH=x86_64
  - PLATFORM=debian PLATFORM_VERSION=8 PACKAGECLOUD_DISTROS="debian/jessie" KERNEL_ARCH=i386
  - PLATFORM=debian PLATFORM_VERSION=8 PACKAGECLOUD_DISTROS="debian/jessie" KERNEL_ARCH=x86_64
  - PLATFORM=debian PLATFORM_VERSION=9 PACKAGECLOUD_DISTROS="debian/stretch" KERNEL_ARCH=i386
  - PLATFORM=debian PLATFORM_VERSION=9 PACKAGECLOUD_DISTROS="debian/stretch" KERNEL_ARCH=x86_64
  - PLATFORM=debian PLATFORM_VERSION=10 PACKAGECLOUD_DISTROS="debian/buster" KERNEL_ARCH=i386
  - PLATFORM=debian PLATFORM_VERSION=10 PACKAGECLOUD_DISTROS="debian/buster" KERNEL_ARCH=x86_64

before_install: ./before-install.sh

script: ./build.sh

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(ls pkg/* | tr "\n" ":")
