version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

executors:
  centos-6:
    docker:
      - image: centos:6
    environment:
      PLATFORM: centos
      PACKAGECLOUD_DISTROS: el/6
  centos-7:
    docker:
      - image: centos:7
    environment:
      PLATFORM: centos
      PACKAGECLOUD_DISTROS: el/7
  centos-8:
    docker:
      - image: centos:8
    environment:
      PLATFORM: centos
      PACKAGECLOUD_DISTROS: el/8
  debian-8:
    docker:
      - image: debian:8
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: debian/jessie
  debian-9:
    docker:
      - image: debian:9
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: debian/stretch
  debian-10:
    docker:
      - image: debian:9
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: debian/buster
  ubuntu-1404:
    docker:
      - image: ubuntu:14.04
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: ubuntu/trusty
  ubuntu-1604:
    docker:
      - image: ubuntu:16.04
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: ubuntu/quantal
  ubuntu-1804:
    docker:
      - image: ubuntu:18.04
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: ubuntu/bionic
  ubuntu-2004:
    docker:
      - image: ubuntu:20.04
    environment:
      PLATFORM: ubuntu
      PACKAGECLOUD_DISTROS: ubuntu/focal

commands:
  install_python:
    parameters:
      executor:
        type: string
      version:
        type: string
        default: 3.8.5
    steps:
      - run: echo 'export PATH="/opt/python/usr/bin:$HOME/.local/bin:$PATH"' >> $BASH_ENV
      - run: |
          if [ "$PLATFORM" = "ubuntu" ]; then
            apt-get update
            apt-get install -y ca-certificates curl git build-essential zlib1g-dev libssl-dev libffi-dev
          elif [ "$PLATFORM" = "centos" ]; then
            yum -y groupinstall 'Development Tools'
            yum -y install git zlib-devel openssl-devel libffi-devel
          fi
      - restore_cache:
          key: python-<< parameters.version >>-<< parameters.executor >>-v4
      - run:
          name: Install Python << parameters.version >>
          command: |
            env
            ls -l /opt/
            ls -l /opt/python
            ls -l /opt/python/bin
            ls -l /opt/python/usr/bin
            if which python; then
              if python -V | grep "<< parameters.version >>"; then
                echo "python << parameters.version >> is already installed."
                exit 0
              else
                echo "python is already installed but it is the wrong version."
              fi
            fi

            echo "python not found - installing."
            rm -rf /opt/python/*
            curl -Lo /tmp/python.tgz https://www.python.org/ftp/python/<< parameters.version >>/Python-<< parameters.version >>.tgz
            tar -C /tmp -zxf /tmp/python.tgz
            cd /tmp/Python-<< parameters.version >>
            ./configure --prefix=/opt/python
            make
            make install
      - save_cache:
          key: python-<< parameters.version >>-<< parameters.executor >>-v4
          paths:
            - /opt/python

jobs:
  build:
    executor: << parameters.executor >>
    working_directory: /opt/sensu-plugins-omnibus
    parameters:
      executor:
        type: string
      arch:
        type: string
    environment:
      KERNEL_ARCH: << parameters.arch >>
    steps:
      - checkout
      - install_python:
          executor: << parameters.executor >>
      - restore_cache:
          key: omnibus-<< parameters.executor >>-<< parameters.arch >>-v2
      - run: ./docker-build.sh
      - save_cache:
          key: omnibus-<< parameters.executor >>-<< parameters.arch >>-v2
          paths:
            - /opt/sensu-plugins-omnibus/local
            - /usr/bin/sensu-install
      - aws-s3/sync:
          arguments: --acl public-read
          aws-access-key-id: ARTIFACTS_KEY
          aws-secret-access-key: ARTIFACTS_SECRET
          aws-region: ARTIFACTS_REGION
          from: pkg
          to: "s3://${ARTIFACTS_BUCKET}/$(date +'%Y-%m-%d_%T')_${CIRCLE_WORKFLOW_ID}"
      
workflows:
  build:
    jobs:
      - build:
          name: centos-6-<< matrix.arch >>
          executor: centos-6
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: centos-7-<< matrix.arch >>
          executor: centos-7
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: centos-8-<< matrix.arch >>
          executor: centos-8
          matrix:
            parameters:
              arch: [ x86_64 ]
      - build:
          name: debian-8-<< matrix.arch >>
          executor: debian-8
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: debian-9-<< matrix.arch >>
          executor: debian-9
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: debian-10-<< matrix.arch >>
          executor: debian-10
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: ubuntu-1404-<< matrix.arch >>
          executor: ubuntu-1404
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: ubuntu-1604-<< matrix.arch >>
          executor: ubuntu-1604
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: ubuntu-1804-<< matrix.arch >>
          executor: ubuntu-1804
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
      - build:
          name: ubuntu-2004-<< matrix.arch >>
          executor: ubuntu-2004
          matrix:
            parameters:
              arch: [ i386, x86_64 ]
